### ISSUE TITLE
Analista DevOps

### ISSUE THREAD

**Issue by marcialwushu** [DevComputaria/CangaceiroDevVagas#34]
Vaga: *Analista DevOps - 100% remota*

Requisitos:
Familiaridade com cultura DevOps, configuração com Código;
Integração Contínua;
 Docker/Kubernetes;
Linguagem de Script;
Automação de Configuração.

Oportunidade para atuar na Fábrica de Software 🚀

Contratação: CLT + Vale alimentação ou refeição (Alelo) + Plano de saúde e odontológico (Amil) + Reembolso de certificação

Possui interesse? envie o seu currículo com a pretensão salarial para amanda.campos@basis.com.br

**Comment by eddygarros** [comment]
Eu tô interessado na posição!
